name: CheckLinks

on:
  pull_request:
  push:

jobs:
  check_html_links_job:
    runs-on: ubuntu-latest
    name: Test links in HTML
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Step test links
        run: npm run links
